Georgia = "saqartvelo"
print(Georgia[5:8])
print(Georgia[0:2] + Georgia[7] + Georgia[4:6] + Georgia[9])
print(Georgia[0:2] + Georgia[8] + Georgia[1])
print(Georgia[0] + Georgia[9] + Georgia[8:10])
print(Georgia[2:10])
print(Georgia[0:2] + Georgia[5] + Georgia[1] + Georgia[6:8])
print(Georgia[5] + Georgia[1] + Georgia[6] + Georgia[8] + Georgia[1])
print(Georgia[8] + Georgia[1] + Georgia[2:4])
print(Georgia[0] + Georgia[4] + Georgia[9] + Georgia[8] + Georgia[1])
print(Georgia[4] + Georgia[1] + Georgia[0:2])
print(Georgia[5:7] + Georgia[8] + Georgia[1])
print(Georgia[8] + Georgia[7] + Georgia[8:10])
print(Georgia[8:10] + Georgia[2] + Georgia[9])
print(Georgia[2] + Georgia[7] + Georgia[4] + Georgia[1])
print(Georgia[2:4] + Georgia[8] + Georgia[1])
print(Georgia[5] + Georgia[1] + Georgia[4] + Georgia[9])
print(Georgia[5] + Georgia[4] + Georgia[1] + Georgia[0:2])
print(Georgia[0:2] + Georgia[5:7] + Georgia[1] +Georgia[8] + Georgia[7])
print(Georgia[5] + Georgia[1] + Georgia[5] + Georgia[1] + Georgia[4] + Georgia[1])
print(Georgia[0:2] + Georgia[4] + Georgia[7] + Georgia[6] + Georgia[7] + Georgia[8] + Georgia[1])